// This file is automatically generated. Do not modify it manually.
// For any changes, run `firebase-frameworks:discover` to regenerate.
/* eslint-disable */

import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  "projectId": "studio-3232403063-8f853",
  "appId": "1:261135036605:web:7d362ed556f6d24fda87d4",
  "apiKey": "AIzaSyBc41pnSQZss7UIeVUkebBwSlAnMgcLTZg",
  "authDomain": "studio-3232403063-8f853.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "261135036605"
};

export function initializeFirebase(): { firebaseApp: FirebaseApp, auth: ReturnType<typeof getAuth>, firestore: ReturnType<typeof getFirestore> } {
  const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
  const auth = getAuth(app);
  const firestore = getFirestore(app);
  return { firebaseApp: app, auth, firestore };
}
